### ISSUE TITLE
关于更极端的信息组合有什么解析的思路吗？

### ISSUE THREAD

**Issue by memorate** [pupuk/addr#2]
例如：
1.张三广东省深圳市南山区腾讯前海大厦23楼16777778888
2.广东省深圳市南山区腾讯前海大厦23楼张三16777778888

PS：没有任何标点符号做分割

个人目前想到的是：
根据库里的数据去匹配 省——>市 然后确定地址在字符串中的index，这样就可以解析上面第一种情况。
但是第二种没任何头绪。。。
感觉这条路也不是很合理

**Comment by pupuk** [comment]
> 例如：
> 1.张三广东省深圳市南山区腾讯前海大厦23楼16777778888
> 2.广东省深圳市南山区腾讯前海大厦23楼张三16777778888
> 
> PS：没有任何标点符号做分割
> 
> 个人目前想到的是：
> 根据库里的数据去匹配 省——>市 然后确定地址在字符串中的index，这样就可以解析上面第一种情况。
> 但是第二种没任何头绪。。。
> 感觉这条路也不是很合理

1.2 这两个文本都能够正常的解析，如下图：
![image](https://user-images.githubusercontent.com/7934974/124269115-0bc04400-db6d-11eb-9622-d1fba0349f4f.png)

根据中国省市县区的地址规律，县/区的名称，是最有识别度的，我们的代码识别，也是优先识别这个，再回源找上一级的市，省。

**Comment by memorate** [comment]
OK，我再看看
