### ISSUE TITLE
解析精度不行，还没有smartParsePro好

### ISSUE THREAD

**Issue by wzhsh90** [pupuk/addr#4]
新疆阿克苏温宿县博孜墩柯尔克孜族乡吾斯塘博村一组306号 150-3569-6956 马云

这个就不能解析

**Comment by wzhsh90** [comment]
省市区建议用这个数据
https://github.com/modood/Administrative-divisions-of-China

**Comment by pupuk** [comment]
> 省市区建议用这个数据 https://github.com/modood/Administrative-divisions-of-China

这个作者参考了我的代码后，我与他交涉以后，他在老项目添加了参考链接，然后马上另起了一个新的版本库。只能对这种做法微微一笑吧。
https://github.com/wzc570738205/smart_parse
